### ISSUE TITLE
Error with modules

### ISSUE THREAD

**Issue by EduSemensato** [JustOptimize/ShowHiddenChannels#201] opened 2024-08-06 09:24 UTC
![erro](https://github.com/user-attachments/assets/65d6319b-d201-4eab-be44-ff2f34a02658)
![shc broken](https://github.com/user-attachments/assets/f4affce8-c795-4097-874f-8ca8701fad91)
![shc](https://github.com/user-attachments/assets/836c20b6-f7db-4f11-bad2-a4a9056e2456)

After presenting the errors, I updated it according to the solution presented at: https://github.com/JustOptimize/ShowHiddenChannels/issues/188#issuecomment-2179264855

And it started returning the error with the attachment named "erro"

**Comment by JustOptimize** [comment] 2024-08-06 09:26
Duplicate of #199

**Closed by JustOptimize** 2024-08-06 09:26 UTC
